import Providers from "./providers";
import "./globals.css";
import {Medula_One} from '@next/font/google' 

const medulaone = Medula_One({
    subsets: ['latin'],
    weight: '400',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={medulaone.className}>
        <Providers>
          <div className="container mx-auto">{children}</div>
        </Providers>
      </body>
    </html>
  );
}